"""Session recording — event models and JSONL recorder."""

from lattice.session.models import (
    AgentDoneEvent,
    AgentResponseEvent,
    AgentStartEvent,
    CLIProgressEvent,
    CLITextChunkEvent,
    CLIThinkingEvent,
    CLIToolCallEvent,
    ErrorEvent,
    LLMCallEndEvent,
    LLMCallStartEvent,
    LoopBoundaryEvent,
    MemorySnapshotEvent,
    MessageEvent,
    SessionEndEvent,
    SessionEvent,
    SessionStartEvent,
    StatusEvent,
    ToolCallEvent,
    ToolResultEvent,
)
from lattice.session.recorder import EndReason, SessionRecorder

__all__ = [
    "AgentDoneEvent",
    "AgentResponseEvent",
    "AgentStartEvent",
    "CLIProgressEvent",
    "CLITextChunkEvent",
    "CLIThinkingEvent",
    "CLIToolCallEvent",
    "EndReason",
    "ErrorEvent",
    "LLMCallEndEvent",
    "LLMCallStartEvent",
    "LoopBoundaryEvent",
    "MemorySnapshotEvent",
    "MessageEvent",
    "SessionEndEvent",
    "SessionEvent",
    "SessionRecorder",
    "SessionStartEvent",
    "StatusEvent",
    "ToolCallEvent",
    "ToolResultEvent",
]
